### ISSUE TITLE
Reformat Code

### ISSUE THREAD

**Issue by frogocomics** [CreepsterLGC/Core#1]
I was looking your code earlier this day and I noticed how strangely formatted everything is.
- Some lines were indented by 8 spaces instead of 4
- Some classes have completely captalized names

I would suggest that you enforce a specific code convention to make your code more human oriented and neat. I personally use the Google Java Code Conventions.

**Comment by CreepsterLGC** [comment]
It's a suggestion worth thinking about. However: at the moment there are a lot of things to do which might be more important than code styling. I will surely fix this when I feel like it. Thanks for suggesting it though!

**Comment by CreepsterLGC** [comment]
Also, the code looks way better on my local computer. (considering the space digits). I think github is messing something up.
