### ISSUE TITLE
Zones set to pvp: deny still allow pvp damage

### ISSUE THREAD

**Issue by GraysonBriggs** [CreepsterLGC/Core#3]
using:
forge: 1.8-11.14.3.1450
sponge: 1.8-1519-2.1DEV-706
Core: 2.5.7d

I set a zone using the golden axe 
used /zone create test
then /zone edit pvp deny

Please let me know if you need any more information.

**Comment by CreepsterLGC** [comment]
Iam aware of that. The problem is that Sponge hasn't implemented any DamageEvents yet. As soon as thats done, players wont be able to damage each other.

Thanks for reporting this issue though!
